# This file was generated by GoReleaser. DO NOT EDIT.
cask "grove" do
  version "0.19.0"

  on_macos do
    on_intel do
      url "https://github.com/SarthakJariwala/grove/releases/download/v#{version}/grove_darwin_amd64.tar.gz",
        verified: "github.com/SarthakJariwala/grove"
      sha256 "94396d194edb66f73517f516860695b9d675f31a0688f03b67642ab9f6f0acb7"
    end
    on_arm do
      url "https://github.com/SarthakJariwala/grove/releases/download/v#{version}/grove_darwin_arm64.tar.gz",
        verified: "github.com/SarthakJariwala/grove"
      sha256 "c6d41358930b3ef2dd5b37c8d6997980247d1ff71331097f5386230af91dfb16"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SarthakJariwala/grove/releases/download/v#{version}/grove_linux_amd64.tar.gz",
        verified: "github.com/SarthakJariwala/grove"
      sha256 "b19a965605231fd02c9618ff9313640650670f3b08ab7805628b727217c49903"
    end
    on_arm do
      url "https://github.com/SarthakJariwala/grove/releases/download/v#{version}/grove_linux_arm64.tar.gz",
        verified: "github.com/SarthakJariwala/grove"
      sha256 "14d0e964bf645015d2dcd6bae2ba58158621847226b94d383970c9c5bc1c8c24"
    end
  end

  name "grove"
  desc "Scale agents, not stress. Calm terminal energy for chaotic agent workflows."
  homepage "https://github.com/SarthakJariwala/grove"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "grove"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grove"]
    end
  end

  # No zap stanza required

end
