# This file was generated by GoReleaser. DO NOT EDIT.
cask "grove" do
  name "grove"
  desc "Scale agents, not stress. Calm terminal energy for chaotic agent workflows."
  homepage "https://github.com/SarthakJariwala/grove"
  version "0.9.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grove"
  depends_on formula: [
      "tmux",
    ]

  on_macos do
    on_intel do
      url "https://github.com/SarthakJariwala/grove/releases/download/v#{version}/grove_darwin_amd64.tar.gz",
        verified: "github.com/SarthakJariwala/grove"
      sha256 "7de18138ba3671cc0a2056ae313adaedd8caaefd6c11d7644e31bb9a9ee1be74"
    end
    on_arm do
      url "https://github.com/SarthakJariwala/grove/releases/download/v#{version}/grove_darwin_arm64.tar.gz",
        verified: "github.com/SarthakJariwala/grove"
      sha256 "1ca9eceb6b0f968d4ca1a196237243ff35b9e61a4a722184f9b391b0c3aa3c03"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SarthakJariwala/grove/releases/download/v#{version}/grove_linux_amd64.tar.gz",
        verified: "github.com/SarthakJariwala/grove"
      sha256 "c960af80ebcc1396bd9b7d27bb92ffaee5b93f22583d7a3141b8b4762c8d8622"
    end
    on_arm do
      url "https://github.com/SarthakJariwala/grove/releases/download/v#{version}/grove_linux_arm64.tar.gz",
        verified: "github.com/SarthakJariwala/grove"
      sha256 "13eea1c8e2dbdde25ab745c355e09cdaee10112ba1bb175c61143d4c36b4d1e7"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grove"]
    end
  end

  # No zap stanza required
end
