# This file was generated by GoReleaser. DO NOT EDIT.
cask "grove" do
  version "0.13.0"

  on_macos do
    on_intel do
      url "https://github.com/SarthakJariwala/grove/releases/download/v#{version}/grove_darwin_amd64.tar.gz",
        verified: "github.com/SarthakJariwala/grove"
      sha256 "6b1b9b263656b713e355397012cc530cb97abb1e456a6e101936f6c5b52f119f"
    end
    on_arm do
      url "https://github.com/SarthakJariwala/grove/releases/download/v#{version}/grove_darwin_arm64.tar.gz",
        verified: "github.com/SarthakJariwala/grove"
      sha256 "a28ee28c76360affd4e1b5e2ab38d8e95f1aeb4426a2477721f45e6f6ec17257"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/SarthakJariwala/grove/releases/download/v#{version}/grove_linux_amd64.tar.gz",
        verified: "github.com/SarthakJariwala/grove"
      sha256 "f3aaa3d528868de569dcb04318f9ab08f1ed367c4797cea701489e69b208f49f"
    end
    on_arm do
      url "https://github.com/SarthakJariwala/grove/releases/download/v#{version}/grove_linux_arm64.tar.gz",
        verified: "github.com/SarthakJariwala/grove"
      sha256 "8056c459cd124ef77f6bc6a24f33c576243c6a8f0a0e235a7ae82b8462388d3a"
    end
  end

  name "grove"
  desc "Scale agents, not stress. Calm terminal energy for chaotic agent workflows."
  homepage "https://github.com/SarthakJariwala/grove"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "grove"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grove"]
    end
  end

  # No zap stanza required

end
